version: "3"

networks:
  internal:

services:
  web:
    build: .
    container_name: heroku-dockerize-web
    networks:
      - internal
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      REDIS_URL: "redis://db:6379"
    depends_on:
      - db
    restart: always

  db:
    image: redis:latest
    container_name: heroku-dockerize-redis
    networks:
      - internal
    restart: always